# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3358ce56ab18b69c38fc84f4b726fb4a139db1006cc95af0d95050a2500c92b0455d7b57486b5970bbe88c031834e77478267dfd69f01418d83c9bf99c61572

test:
  secret_key_base: 17f65c45a7c7932ce27dc597754066a2c229c07437ccdda0c3e8585d8a6e75d4143a24c8ade798a032830ab8e4cfd3e61bb03e97c1a73a79536a166fc382a172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
